import { createApi, fetchBaseQuery } from '@reduxjs/toolkit/query/react';

export const baseApi = createApi({
  baseQuery: fetchBaseQuery({ baseUrl: '/api' }),
  tagTypes: [
    'AllUsers',
    'ArtistBalance',
    'ArtistNftContract',
    'Auction',
    'AuctionState',
    'Config',
    'DropAllowlist',
    'EscrowPoints',
    'Following',
    'Nfts',
    'CollectionMintCount',
    'OpenEditionMintCount',
    'PendingDrops',
    'PlatformRoyaltyAddress',
    'PrimaryPlatformCut',
    'Prizes',
    'SocialFeed',
    'SocialMessages',
    'SocialProfile',
    'SocialPost',
    'SocialTokenBoard',
    'Refunds',
    'TicketCount',
    'User',
    'UserPoints',
    'Wallet',
  ],
  endpoints: () => ({}),
});
